export const CART_REQUEST = "CART_REQUEST"
export const CART_REQUEST_SUCCESS = "CART_REQUEST_SUCCESS"
export const CART_REQUEST_FAIL = "CART_REQUEST_FAIL"

export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST"
export const CART_REMOVE_REQUEST_SUCCESS = "CART_REMOVE_REQUEST_SUCCESS"
export const CART_REMOVE_REQUEST_FAIL = "CART_REMOVE_REQUEST_FAIL"


export const CART_EMPTY = "CART_EMPTY"
